ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: postgres
  password: postgres
redis:
  host: "localhost"
  port: 6379